name: Sync to S3

on:
  push:
    branches:
      - master

env:
  AWS-REGION: ap-southeast-1
  AWS-URL: beta-programming-in-th
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  deploy:
    name: Upload to Amazon S3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Change relative path to absolute path
        run: sed -i -e 's+../media/+https://${{ env.AWS-URL }}.s3-${{ env.AWS-REGION }}.amazonaws.com/solutions/media/+g' *
        working-directory: ./md

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS-REGION }}

      - name: Copy files to S3 with the AWS CLI
        run: |
          aws s3 sync . s3://${{ env.AWS-URL }}/solutions --exclude "*" --include "md/*" --include "media/*" --acl public-read
